### ISSUE TITLE
Setup release-plan to work with pre-majors

### ISSUE THREAD

**Issue by mansona** [adopted-ember-addons/ember-paper#1282]
If we were to merge https://github.com/adopted-ember-addons/ember-paper/pull/1281 right now it would release v1.0.0 of this project, which we don't want 🙈 

With https://github.com/embroider-build/release-plan/pull/68 we can configure a breaking change to be a `pre-major` and it would continue to release beta versions of the library.

**Comment by matthewhartstonge** [comment]
fixed via #1302 #1316
